version: "3.7"
services:
  influxdb:
    image: influxdb:1.7.9-alpine
    container_name: influxdb_load
    env_file:
      - "influxdb.env"
    ports:
      - "8086:8086"

  grafana:
    build:
      context: "grafana"
    container_name: grafana_load
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
